In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/after_ingestion_insurance.csv")

Check how many unique values each column has ??

In [7]:
def check_unique_values(df):
    col_names = []
    col_unique_values = []
    for col in df:
        if df[col].dtype == 'object':
            col_names.append(str(col))
            col_unique_values.append(df[col].nunique())
    unique_val_table = pd.DataFrame()
    unique_val_table["Col Name"] = col_names
    unique_val_table["Unique Values"] = col_unique_values
    unique_val_table = unique_val_table.sort_values(by='Unique Values', ascending=False)
    return unique_val_table

In [8]:
unique_table = check_unique_values(df)
unique_table

                   Col Name  Unique Values
15        incident_location           1000
0          policy_bind_date            951
8             incident_date             60
19               auto_model             39
6           insured_hobbies             20
18                auto_make             14
5        insured_occupation             14
4   insured_education_level              7
14            incident_city              7
13           incident_state              7
7      insured_relationship              6
12    authorities_contacted              4
10           collision_type              4
11        incident_severity              4
9             incident_type              4
1              policy_state              3
16          property_damage              3
17  police_report_available              3
2                policy_csl              3
3               insured_sex              2
20           fraud_reported              2